-- =============================================
-- FF11 装備・素材・ポイント管理アプリ DB定義 (完全版)
-- =============================================

-- 1. ユーザープロフィール
-- ログインユーザーの基本情報
create table profiles (
  id uuid references auth.users not null primary key,
  username text,
  avatar_url text
);

-- 2. ゲームアカウント
-- 1ユーザーが持つ「メイン垢」「倉庫垢」などの管理
create table game_accounts (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) not null,
  account_name text not null, -- 例: "メイン垢"
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. キャラクター
-- アカウントごとのキャラ管理
create table characters (
  id uuid default gen_random_uuid() primary key,
  account_id uuid references game_accounts(id) not null,
  name text not null,
  server text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. アイテムマスター (武器・防具・素材・ポイント すべて統合)
create table items (
  id integer primary key,     -- ゲーム内IDまたは独自ID
  name text not null,         -- 名前 (例: "リフトシンダー", "ビーズ")
  
  -- カテゴリ分け
  category text not null,     -- 'weapon', 'armor', 'material', 'currency'
  sub_category text,          -- 'Relic', 'Artifact', 'Empyrean', 'Point'(ホールマーク等)
  
  -- 装備品用データ (素材の場合はNULL)
  jobs text[],                -- 装備可能ジョブ ['WAR', 'PLD']
  equip_slot text,            -- 'Head', 'Body', 'Main' ...
  item_level integer,         -- 119, 99
  
  -- ステータス (JSON形式で柔軟に保存)
  -- 例: {"STR": 10, "Accuracy": 20, "Haste": 5, "Store TP": 10}
  stats jsonb default '{}',

  -- 表示・管理用
  image_url text,
  wiki_url text,              -- 用語辞典リンク
  
  -- 在庫管理プロパティ
  is_ex boolean default false,         -- 宅配不可 (Ex)
  is_rare boolean default false,       -- 1つしか持てない (Rare)
  can_send_account boolean default true, -- 同アカ宅配可
  stack_size integer default 12        -- 1枠のスタック数
);

-- 5. レシピ・入手経路 (合成・交換・強化)
create table recipes (
  id integer generated by default as identity primary key,
  result_item_id integer references items(id) not null,   -- 完成品/入手品
  
  -- レシピの種類
  -- 'synthesis': 合成/錬成
  -- 'upgrade': 装備強化 (AF+1 -> AF+2)
  -- 'exchange': ポイント交換 (ビーズ -> アイテム)
  recipe_type text default 'upgrade', 

  base_item_id integer references items(id),              -- 元装備 (強化時のみ)
  material_item_id integer references items(id) not null, -- 必要素材/必要ポイント
  quantity integer default 1,                             -- 必要個数/必要ポイント数
  
  acquisition_note text -- メモ (例: "マウラ NPC:Gorney")
);

-- 6. インベントリ (所持数・ポイント管理)
-- ポイント(ガリモ等)もここに quantity として記録します
create table inventories (
  id uuid default gen_random_uuid() primary key,
  character_id uuid references characters(id) not null,
  item_id integer references items(id) not null,
  quantity integer default 0,
  
  -- 保管場所 ('inventory', 'safe', 'storage', 'point_wallet'など)
  location text default 'inventory',
  
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(character_id, item_id, location)
);

-- 7. ターゲット設定
-- ユーザーが「今、これを作りたい！」と設定している目標
create table user_targets (
  id uuid default gen_random_uuid() primary key,
  character_id uuid references characters(id) not null,
  
  -- 何をターゲットにするか
  target_type text not null, -- 'job_gear'(AF等), 'weapon_creation'(ミシック等)
  target_name text not null, -- 'WAR' または 'Burtgang'など
  
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(character_id, target_type, target_name)
);

-- 8. 進捗管理 (シミュレーター用)
-- 「戦士AF足は今IL109まで作った」という記録
create table gear_progression (
  id uuid default gen_random_uuid() primary key,
  character_id uuid references characters(id) not null,
  
  -- どの系列のどの部位か
  group_name text not null,   -- 'Artifact', 'Relic', 'Empyrean'
  job_code text,              -- 'WAR' (武器ならNULL可)
  slot text not null,         -- 'Feet', 'Main'
  
  current_item_id integer references items(id), -- 現在持っているランク
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- セキュリティポリシー (RLS) の設定
-- 開発中は「ログインしていれば自由に読み書き可能」にします
alter table profiles enable row level security;
alter table game_accounts enable row level security;
alter table characters enable row level security;
alter table inventories enable row level security;
alter table user_targets enable row level security;
alter table gear_progression enable row level security;

create policy "Auth access profiles" on profiles for all using (auth.role() = 'authenticated');
create policy "Auth access accounts" on game_accounts for all using (auth.role() = 'authenticated');
create policy "Auth access characters" on characters for all using (auth.role() = 'authenticated');
create policy "Auth access inventories" on inventories for all using (auth.role() = 'authenticated');
create policy "Auth access targets" on user_targets for all using (auth.role() = 'authenticated');
create policy "Auth access progression" on gear_progression for all using (auth.role() = 'authenticated');

-- マスタデータ(items, recipes)は全員読み取り許可
alter table items enable row level security;
alter table recipes enable row level security;
create policy "Public read items" on items for select using (true);
create policy "Public read recipes" on recipes for select using (true);

-- ユーザー登録時に自動でプロフィール作成するトリガー
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, username)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();